const ADD_SUCCESS = 'posts/ADD_SUCCESS';
const DELETE_SUCCESS = 'posts/DELETE_SUCCESS';
const UPDATE_SUCCESS = 'posts/UPDATE_SUCCESS';
// const GET_POST = 'posts/GET_POST';

// синхронные операции:
const CHANGE_FILTER = 'posts/CHANGE_FILTER';

const FETCH_REQUEST = 'posts/FETCH_REQUEST';
const FETCH_SUCCESS = 'posts/FETCH_SUCCESS';
const FETCH_ERROR = 'posts/FETCH_ERROR';

export default {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  UPDATE_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
