const ADD = 'notes/ADD';
const DELETE = 'notes/DELETE';
const TOGGLE_COMPLETED = 'notes/TOGGLE_COMPLETED';
const CHANGE_FILTER = 'notes/CHANGE_FILTER';

const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS = 'notes/FETCH_SUCCESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

export default {
  ADD,
  DELETE,
  TOGGLE_COMPLETED,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
